from django.urls import path

from .views import (
    index,
    DishTypeListView,
    DishTypeDetailView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    IngredientListView,
    IngredientCreateView,
    IngredientUpdateView,
    IngredientDeleteView, CookListView, CookDetailView, CookCreateView, CookUpdateView, CookDeleteView
)

urlpatterns = [
    path("", index, name="index"),
    path("dish_type/",
         DishTypeListView.as_view(),
         name="dish-type-list"),
    path("dish_type/<int:pk>/detail/",
         DishTypeDetailView.as_view(),
         name="dish-type-detail"),
    path("dish_type/create/",
         DishTypeCreateView.as_view(),
         name="dish-type-create"),
    path("dish_type/<int:pk>/update/",
         DishTypeUpdateView.as_view(),
         name="dish-type-update"),
    path("dish_type/<int:pk>/delete/",
         DishTypeDeleteView.as_view(),
         name="dish-type-delete"),
    path("ingredients/",
         IngredientListView.as_view(),
         name="ingredients-list"),
    path("ingredients/create/",
         IngredientCreateView.as_view(),
         name="ingredients-create"),
    path("ingredients/<int:pk>/update/",
         IngredientUpdateView.as_view(),
         name="ingredients-update"),
    path("ingredients/<int:pk>/delete/",
         IngredientDeleteView.as_view(),
         name="ingredients-delete"),
    path("cooks/",
         CookListView.as_view(),
         name="cooks-list"),
    path("cook/<int:pk>/detail/",
         CookDetailView.as_view(),
         name="cook-detail"),
    path("cook/create/",
         CookCreateView.as_view(),
         name="cook-create"),
    path("cook/<int:pk>/update/",
         CookUpdateView.as_view(),
         name="cook-update"),
    path("cook/<int:pk>/delete/",
         CookDeleteView.as_view(),
         name="cook-delete"),
]

app_name = "kitchen"
