# Generated by Django 4.2.1 on 2023-06-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cook",
            name="year_of_experience",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dish",
            name="descriptions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
