# Generated by Django 4.2.2 on 2023-06-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0002_cook_year_of_experience_dish_descriptions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="dish_cost",
        ),
        migrations.AlterField(
            model_name="dish",
            name="descriptions",
            field=models.TextField(default="This is the best dish in the world "),
        ),
    ]
